version: "3"
services:
  index_front:
    container_name: index_front
    image: logotipiwe/index_front
#    build:
#      context: .
#      args:
#        - --no-cache
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dc-net
    environment:
      BACK_PATH: /bek
networks:
  dc-net:
    external: true