version: "3"
services:
  index_front:
    container_name: index_front
    image: ${IMAGE}
    networks:
      - dc-net
    environment:
      BACK_PATH: /index_back
networks:
  dc-net:
    external: true